gotestyourself/gotestsum

- .circleci/config.yml
- .gitignore
- Gopkg.lock
- Gopkg.toml
- cmd/handler.go
- cmd/main.go
- internal/junitxml/report.go
- scripts/test-unit
- testjson/execution.go
- testjson/execution_test.go
- testjson/printer.go
- testjson/printer_test.go
- testjson/summary.go
- testjson/summary_test.go
Closes #4
Add flags to optionally output a JUnit XML file, or a JSON file with all the TestEvents.
> Support JUnit XML and TestEvent JSON output files

- .circleci/config.yml
- Gopkg.lock
- Gopkg.toml
- main.go
I noticed some strange behaviour with `gotestsum` when I used `go get` to download dependencies. When I used unknown flags it was not giving me any error. I guess there is a regression in `spf13/pflag`(see https://github.com/spf13/pflag/issues/176)
Update vendor to pickup the latest changes, and update flag parsing logic to handle the new behaviour.
Also fix a panic with `--raw-command`
> Fix vendor, update to new spf13/pflag behaviour

- Gopkg.lock
- internal/junitxml/report.go
- internal/junitxml/report_test.go
Fixes #30 
The version reported by runtime.Version() may not be correct for the version running
the tests.
> Use go version as reported by the binary

- testjson/pkgpathprefix.go
- testjson/pkgpathprefix_test.go
- testjson/printer.go
- testjson/printer_test.go
There is no public API for finding and reading the go.mod file, so copy some internals
from go to locate and read the package line from the go.mod file
> Support relative pkg paths with go modules

- go.mod
- testjson/execution.go
These lines are printed when a go command runs for the first time on
go1.11 and a go.mod does not yet exist.
> Add more go module stderr lines to the whitelist

- internal/junitxml/report.go
- internal/junitxml/testdata/junitxml-report.golden
- testjson/summary.go
It appears that `time` is generally just a `double` and does not have a unit suffix.
> Remove s suffix from junitxml times

- internal/junitxml/report.go
- internal/junitxml/testdata/junitxml-report.golden
Output the full classname in the classname attribute of testcase elements, instead of a classname with the package name removed.
This is consistent with the description for the testcase classname attribute described in https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd ("Full class name for the class the test method is in.")
> Output full classname as testcase classname attribute value

- main.go
I wasn't sure whether there was any mileage in trying to write some tests for this.
> Add a --version flag that goreleaser will populate for us

- go.sum
- testjson/execution.go
- testjson/execution_test.go
- testjson/format.go
- testjson/format_test.go
- testjson/generate.sh
- testjson/testdata/go-test-json-with-cover.err
- testjson/testdata/go-test-json-with-cover.out
- testjson/testdata/short-format-coverage.err
- testjson/testdata/short-format-coverage.out
- testjson/testdata/standard-quiet-format-coverage.err
- testjson/testdata/standard-quiet-format-coverage.out
Closes #56
Identify coverage output events with string comparison. There does not appear to be another way.
Add coverage output to the short format, and filter out the duplicate line from the standard-quiet output.
> Identify and, filter or display coverage output

- testjson/execution.go
- testjson/format.go
- testjson/format_test.go
- testjson/testdata/short-format-coverage.out
- testjson/testdata/short-format.out
- testjson/testdata/short-verbose-format.out
Closes #58
Include `(cached)` in the output if a package is cached
> Report if a package was cached in short formats

- main.go
Signed-off-by: Eric Billingsley <eric@calculi.com>
> always colorize output unless specifically requested not to

- testjson/format.go
Prevents output that looks like this:
```
PASS ..TestHeader/readNegativeLength (0.00s)
PASS ..TestHeader/lengths/124 (0.00s)
PASS ..TestHeader/lengths/131072 (0.00s)
PASS ..TestHeader/lengths/65535 (0.00s)
PASS ..TestHeader/lengths/65537 (0.00s)
PASS ..TestHeader/lengths/65536 (0.00s)
PASS ..TestHeader/lengths/4096 (0.00s)
PASS ..TestHeader/lengths/16384 (0.00s)
PASS ..TestHeader/lengths/125 (0.00s)
PASS ..TestHeader/lengths/126 (0.00s)
PASS ..TestHeader/lengths (0.01s)
PASS ..TestHeader/fuzz (0.33s)
PASS ..TestHeader (0.00s)
```
We don't want the double dots if the test is in the CWD.
> Improve short-verbose output for tests in CWD

- README.md
- flags.go
- handler.go
- internal/junitxml/report.go
- internal/junitxml/report_test.go
- main.go
- testjson/format.go
- testjson/pkgpathprefix.go
- testjson/pkgpathprefix_test.go
- testjson/summary.go
Fixes #50 
Fixes #68 
Closes #69 
Add new command line flags for configuring the format of the junit-xml output.
The flag names are unfortunately quite long, but I think shorter names might not be sufficient in this case.
> Junit XML name formats

- README.md
- main.go
- testjson/format.go
Closes #72
Adds a new format, similar to `short`, that prints test output as soon as a test fails. Useful when a test suite runs for a long time and you want to see errors before the run ends.
> Add short-with-failures format

- main.go
Follow up to #63
Predicting color from the environment instead of defaulting to false is probably the correct default.
> Default no-color to library value

- testjson/dotformat.go
- testjson/dotformat_test.go
Fixes #82 
Seems difficult to reproduce in a test, but this should fix it
> Fix panic when terminal width is 0

- README.md
- main.go
- testjson/format.go
`short` and `short-verbose` don't say very much about the format.
> Some possible new names for the formats

- .circleci/config.yml
- internal/dotwriter/writer.go
- internal/dotwriter/writer_posix.go
- internal/dotwriter/writer_windows.go
- main.go
- testjson/dotformat.go
- testjson/format.go
- testjson/testdata/dots-format-windows.out
- testjson/testdata/dots-format.out
Relates to #88
Restore the old `dots` format. Use `dots-v2` for the new dynamic format.
Attempt to fix the v2 output with some leading empty new lines.
> Re-add the original dots format

- README.md
- docs/running-without-go.md
Fixes #96 
This seems to be required to get elapsed time. See https://github.com/gotestyourself/gotestsum/issues/96
> Add -t flag to test2json examples

- .circleci/config.yml
- .golangci.yml
Instead of an exclude list. This way the addition of new linters in golangci-lint does not cause errors.
> Use an explicit list of linters

- testjson/execution.go
- testjson/execution_test.go
- testjson/format_test.go
- testjson/summary.go
- testjson/summary_test.go
- testjson/testdata/go-test-json-missing-test-fail.out
- testjson/testdata/summary-missing-test-fail-event
Related to #94, #99 
If a test panics it may never send a final ActionFail event. By tracking the
running tests we can add any incomplete tests to Failed when the execution
ends.
This behaviour changed in go1.14. See golang/go#38382 (comment)
> Print incomplete tests as failures in the summary

- internal/junitxml/report.go
- testjson/execution.go
- testjson/execution_test.go
- testjson/format.go
- testjson/summary.go
- testjson/summary_test.go
- testjson/testdata/go-test-json-misattributed.out
- testjson/testdata/summary-misattributed-output
- testjson/testdata/summary-root-test-has-subtest-failures
See golang/go#29755, which may be fixed by https://github.com/golang/go/pull/34419 if that is merged. Even if that fix makes it into go1.15 there will be plenty of projects still running earlier versions of Go, so a workaround may be useful for another year or more.
Related to #64, #66
If a test fails, and there is no test output (other than framing), then print all the test output for the entire test case.
This won't fix the issue if the test which failed had some output, but well behaved tests generally shouldn't non-failure message output, so hopefully this case is rare.
> mitigate test2json bug causing missing test output

- testjson/execution.go
- testjson/summary.go
- testjson/testdata/summary-missing-test-fail-event
Pause and continue lines may be in the output. The other conditions in this function should be correct on their own for determining if additional lines need to be returned.
> Tests can have more than 2 framing lines

- .pre-commit-hooks.yaml
This enables using gotestsum as a pre-commit hook via the https://pre-commit.com/ framework.
> Add a pre-commit hook configuration

- cmd/cmd.go
- cmd/tool/cmd.go
- cmd/tool/slowest/ast.go
- cmd/tool/slowest/ast_test.go
- cmd/tool/slowest/slowest.go
- cmd/tool/slowest/slowest_test.go
- go.mod
- go.sum
- internal/junitxml/report_test.go
- log/log.go
- main.go
- testjson/execution.go
- testjson/summary_test.go
Example usage in the source.
Keep local development fast by identifying slow tests and automatically marking them with a `t.Skip` on some condition.
> cmd/tool/slowest: Print or mark slowest tests

- do
pass the arg, and use it in the iidfile cache filename so that using a different value doesn't keep using the same cached image id.
> do: use GOLANG_VERSION arg

- go.mod
- go.sum
This version plays well with go1.13 and up "wrapped" errors, and makes sure that `errors.Unwrap()`, `errors.Is()` and `errors.As()` are able to get the wrapped error.
> update pkg/errors to v0.9.1

- internal/dotwriter/writer_windows.go
Looks like this is now provided by golang.org/x/sys as well. The other ones not yet (afaics)
Perhaps  @tklauser knows if that's within scope of golang.org/x/sys, or if we need to continue implementing it here
(note; I don't have a Windows machine running, so have not tested it)
> Use golang.org/x/sys/windows.GetConsoleScreenBufferInfo

- cmd/tool/slowest/slowest.go
- do
- handler.go
- testjson/doc.go
- testjson/execution.go
- testjson/execution_test.go
Also make ScanTestOutput easier to use.
Adds `godoc` to project tasks for previewing doc changes.
> Better docs for testjson package

- cmd/tool/slowest/slowest.go
Also support GOTESTSUM_JSONFILE env var.
> cmd/tool/slowest: Improve help text

- go.mod
- go.sum
https://github.com/spf13/pflag/pull/259
The old behaviour could be confusing because the `-test.x` flags never got through to the go binary.
> Update pflag to remove the -test.x flag dropping

- testjson/execution.go
- testjson/summary_test.go
- testjson/testdata/bug-missing-skip-message-summary.out
- testjson/testdata/go-test-json-missing-skip-msg.out
Caused by deleting the output of all subtests once a root test passes. The skip message of any subtests were lost.
> summary: Fixed missing skip message bug

- internal/junitxml/report.go
- testjson/execution.go
- testjson/execution_test.go
- testjson/format.go
- testjson/format_test.go
- testjson/summary_test.go
- testjson/testdata/bug-repeated-test-case-output.out
Fixes #119
So that when a test case is encountered multiple times, either because -count=n was used, or because ScanTestOutput is being passed multiple test runs, a failure or skipped test displays only its own output, not that of all tests with the same name.
Also move addTestEvent to Package, it is more appropriate as a Package method, and make Package methods use a pointer receiver. Many of them update the Package.
Also remove the need for hasSubtestSkipped by using the Skipped list to determine if a subtest has been skipped.
> Store test output by ID

- cmd/tool/slowest/slowest.go
- cmd/tool/slowest/slowest_test.go
- cmd/tool/slowest/testdata/cmd-flags-help-text
- do
- flags.go
- handler.go
- handler_test.go
- internal/text/testing.go
- main.go
- main_e2e_test.go
- main_test.go
- rerunfails.go
- testdata/e2e/expected/TestE2E_RerunFails/reruns_continues_to_fail
- testdata/e2e/expected/TestE2E_RerunFails/reruns_continues_to_fail-go1.14
- testdata/e2e/expected/TestE2E_RerunFails/reruns_until_success
- testdata/e2e/expected/TestE2E_RerunFails/reruns_until_success-go1.14
- testdata/e2e/flaky/flaky_test.go
- testdata/event-handler-missing-test-fail-expected
- testdata/gotestsum-help-text
- testjson/dotformat_test.go
- testjson/execution.go
Adds a new `--rerun-fails[=n]` flag. When the flag is used `gotestsum` will rerun any failed tests up to `n` times until each one passes at least once.
The new feature can be used to mitigate the pain of flaky tests in CI. To avoid unnecessarily rerunning tests when there is a bug or problem with the test environment, if there are more than 10 failed tests, rerun will be skipped. The `--rerun-fails-max-failures` flag can be used to change that threshold.
Using the `--rerun-fails` flag along with `--raw-command` or with `go test` args may require special handling, which will need to be documented in #117
> Rerun failed tests

- do
- flags.go
- flags_test.go
- main.go
- main_e2e_test.go
- rerunfails.go
- testdata/e2e/expected/TestE2E_RerunFails/first_run_has_errors,_abort_rerun
- testdata/e2e/expected/TestE2E_RerunFails/first_run_has_errors,_abort_rerun-go1.14
- testdata/e2e/expected/TestE2E_RerunFails/reruns_continues_to_fail
- testdata/e2e/expected/TestE2E_RerunFails/reruns_continues_to_fail-go1.14
- testdata/e2e/expected/TestE2E_RerunFails/reruns_until_success
- testdata/e2e/expected/TestE2E_RerunFails/reruns_until_success-go1.14
* add a `DONE` line after each attempt
* abort the rerun if any run has errors
* warn if `go test` exits with any code other than 0 or 1
* `./do update-golden` runs go1.13 in a container to update both sets of golden files
* some misc improvements to naming
> bug fixes for rerun fails

- README.md
> [0.5]  Add docs for new features to README

- main.go
- rerunfails.go
- testdata/e2e/expected/TestE2E_RerunFails/reruns_continues_to_fail
- testdata/e2e/expected/TestE2E_RerunFails/reruns_continues_to_fail-go1.14
- testdata/e2e/expected/TestE2E_RerunFails/reruns_until_success
- testdata/e2e/expected/TestE2E_RerunFails/reruns_until_success-go1.14
- testjson/execution.go
- testjson/format.go
- testjson/format_test.go
- testjson/summary.go
- testjson/summary_test.go
- testjson/testdata/summary-with-run-id.out
This should help make the re-runs easier to see. 
* If the `testname` format is used, the re-runs will include a `(re-run #)` on the Pass/Fail line.
* The failure summary will include a `(re-run #)` on the Fail line
* The DONE line will include the number of runs when there is more than 1
Also makes an exit status that is not 0 or 1 an error that aborts re-runs.
> Add re-run number to testname format, and summary

- testjson/internal/parallelfails/fails_test.go
- testjson/summary.go
- testjson/summary_test.go
- testjson/testdata/go-test-json-with-parallel-fails.out
- testjson/testdata/summary-parallel-failures.out
These lines are necessary when the tests are running in parallel, but when the summary is being printed all the tests are complete, so they are only noise.
> Remove PAUSE and CONT lines from summary output

- .golangci.yml
- main.go
- rerunfails.go
- rerunfails_test.go
- testdata/TestWriteRerunFailsReport-expected
- testdata/go-test-json-flaky-rerun.out
- testdata/gotestsum-help-text
- testjson/execution.go
The report can be used in a CI job to report which tests flaked, so that flaky tests are still visible.
> Rerun fails report

- .goreleaser.yml
We are trying to use gotestsum on arm64 box. We've successfully compiled and run it on the box ourselves, but it would be useful if the packages were just available.
* I've run a hand-compiled version on an arm64 box successfully.
* I've run goreleaser locally and the build was successful
```
$ goreleaser --snapshot --skip-publish --rm-dist
• releasing...
• loading config file       file=.goreleaser.yml
• running before hooks
• loading environment variables
• getting and validating git state
• releasing v0.5.1, commit f9e3d29fa4ca41477cee3177bd4bf03de789d60f
• pipe skipped              error=disabled during snapshot mode
• parsing tag
• setting defaults
• snapshotting
• github/gitlab/gitea releases
• project name
• building binaries
• creating source archive
• archives
• linux packages
• …
```
> Build arm64 binaries

- internal/signalhandlerdriver/main.go
- internal/text/testing.go
- main.go
- main_e2e_test.go
Some test binaries may want to handle SIGINT to perform cleanup of
external resources. This signal handler will forward the interrupt
signal to the 'go test' process to give it a chance to cleanup before
shutting down.
> Add a signal handler to forward SIGINT to 'go test'

- README.md
- rerunfails.go
- rerunfails_test.go
Fixes #148
Both the compiled binary and the 'go test' command accept -test.run, but only 'go test' accepts -run. Change the flag so that rerun works with a compiled binary.
> Fix rerun-fails with compiled test binary

- README.md
- cmd/flags.go
- cmd/flags_test.go
- cmd/main.go
- cmd/main_test.go
- cmd/testdata/e2e/expected/TestE2E_RerunFails/reruns_continues_to_fail
- cmd/testdata/e2e/expected/TestE2E_RerunFails/reruns_continues_to_fail-go1.13
- cmd/testdata/e2e/expected/TestE2E_RerunFails/reruns_until_success
- cmd/testdata/e2e/expected/TestE2E_RerunFails/reruns_until_success-go1.13
- cmd/testdata/gotestsum-help-text
- testjson/summary.go
- testjson/summary_test.go
- testjson/testdata/bug-missing-skip-message-summary.out
- testjson/testdata/bug-repeated-test-case-output.out
- testjson/testdata/summary-misattributed-output
- testjson/testdata/summary-missing-test-fail-event
- testjson/testdata/summary-parallel-failures.out
- testjson/testdata/summary-root-test-has-subtest-failures
- testjson/testdata/summary-with-run-id.out
`--no-summary` is now hidden.
When `--hide-summary=output` is set, remove the newlines between test names.
Remove the extra newline between sections of the summary.
> summary: fewer newlines and rename the no-summary flag to hide-summary

- README.md
- cmd/main.go
- cmd/testdata/gotestsum-help-text
- go.mod
- go.sum
- internal/filewatcher/watch.go
This just happens to work super well with #147. Sending `ctrl-c` while tests are running will cancel the run. Sending `ctrl-c` when no tests are running will exit.
> Add --watch flag for running tests when files change.

- cmd/rerunfails.go
- cmd/rerunfails_test.go
- cmd/tool/slowest/ast.go
- cmd/tool/slowest/slowest.go
- cmd/tool/slowest/slowest_test.go
- internal/junitxml/report.go
- testjson/execution.go
- testjson/summary.go
These small methods on a `type TestName string` make the `IsSubTest` conditional a lot more explicit.
> testjson: create TestName

- README.md
- internal/filewatcher/term_bsd.go
- internal/filewatcher/term_linux.go
- internal/filewatcher/term_unix.go
- internal/filewatcher/term_windows.go
- internal/filewatcher/watch.go
When watching for file changes, pressing the `r` key will re-run tests for the last
package that was run.
Also, mostly incidentally because of the terminal mode, removes echo'ing of characters
pressed while in watch mode. The newline character is handled as a special case
and printed to stdout so that it is still possible to clear part of the screen while
in watch mode.
Only works on unix (not windows), and has only been tested on linux.
> Add rerun for --watch mode

- cmd/handler.go
- cmd/handler_test.go
- cmd/main.go
- cmd/main_e2e_test.go
- cmd/rerunfails.go
- cmd/testdata/e2e/expected/TestE2E_MaxFails_EndTestRun
- cmd/testdata/gotestsum-help-text
- testjson/execution.go
- testjson/execution_test.go
Also fixes a bug where failures from reading stdout/stderr would not actually stop the test run.
Related upstream issue https://github.com/golang/go/issues/33038
> Add --max-fails flag for ending the test run

- cmd/tool/slowest/slowest.go
- cmd/tool/slowest/slowest_test.go
- cmd/tool/slowest/testdata/cmd-flags-help-text
- internal/aggregate/slowest.go
- internal/aggregate/slowest_test.go
- testjson/execution.go
- testjson/execution_test.go
Also extract some functions from `cmd/tool/slowest` so they can be used in the future for test metrics.
> Add TestCase.Time

- internal/filewatcher/term_unix.go
- internal/filewatcher/term_windows.go
- internal/filewatcher/watch.go
Fixes a bug from #160
Previous the terminal would not be reset because the defer was in the
redo handler goroutine. This goroutine accepts a context, but because it
blocks on reading from stdin, it does not exit when the context is
cancelled.
To fix the problem, the defer is moved into the main goroutine.
> watch: properly reset terminal after idle timeout

- cmd/main_test.go
Once a table test grows past a certain point it becomes very difficult
to work with. A failure in one case requires scrolling around attempting
to find the case, because the failure message only includes the line in
the test function, not the testCase.
Instead of a slice or map of test cases, using this runCase function to
add a t.Log will give the line number of the testCase as well as the
line number in the test function. This makes it very easy to jump to
both of the relevant lines.
Best viewed with [hide whitespace changes](https://github.com/gotestyourself/gotestsum/pull/166/files?diff=split&w=1).
> Try out a new pattern for large table tests

- cmd/tool/slowest/ast.go
Initially I assumed that the root test would include all the time of the
subtests, but that is not always the case. With t.Parallel it appears
that root tests can report 0 elapsed time, while subtests can be very
slow.
To fix this problem, if slowest receives any subtest as one of the slow
tests it will skip the root test. This is necessary because adding a
skip statement to a subtest is substantially more complicated than
adding one to the root test. It's much harder to find the correct place
in the AST to add the if statement.
> slowest: skip root tests when subtests are slow

- internal/filewatcher/watch.go
See https://www.joeshaw.org/dont-defer-close-on-writable-files/
> ensure filehandles are closed

- cmd/main.go
- cmd/watch.go
- internal/filewatcher/watch.go
To provide a bit more context when something fails.
Closes #171
> Wrap a couple errors from filewatcher

- cmd/flags.go
- cmd/main.go
- cmd/tool/slowest/slowest.go
- go.mod
- go.sum
Fixes #176
Closes #177
The replace directive was preventing the new go1.16 support for running `go install gotest.tools/gotestsum@latest`.
Since upstream has not yet merged the PR to remove special handling for `-test.x` flags, replace the upstream with my fork.
> Replace spf13/pflag with dnephin/pflag

- .circleci/config.yml
> Use go1.16 for build and publish jobs in CI

- testjson/execution.go
- testjson/execution_test.go
Fixes #189
The check for coverage output was a little too strict. It was only matching coverage output by the -cover flag. The -coverpkg output is a little different.
This commit fixes the check, and adds tests for both.
> Fix capturing of coverpkg output

- internal/junitxml/testdata/junitxml-report.golden
- testjson/dotformat_test.go
- testjson/execution.go
- testjson/format.go
- testjson/format_test.go
- testjson/testdata/dots-format.out
- testjson/testdata/go-test-json.out
- testjson/testdata/go-test-verbose.out
- testjson/testdata/short-format.out
- testjson/testdata/short-verbose-format.out
- testjson/testdata/standard-quiet-format.out
Fixes #140
An output event with this text is sent when 'go test' runs a package that has test files but no tests.
Update two formts that were printing this message in a way that was confusing. Now the standard-quiet format
properly matches 'go test' format, and the testname format omits the text. Since gotestsum includes a count
of tests run in the summary line, this message doesn't seem like it provides much value.
> format: handle 'testing: warning: no tests to run' event

- cmd/main_test.go
- cmd/rerunfails.go
- testjson/execution.go
Mitigates the upstream go bug: https://github.com/golang/go/issues/45508
Since re-running tests requires knowledge of all tests, attempting a re-run after a panic is not safe. `gotestsum` will not be aware of any of the tests that did not run, so many tests could be skipped if a rerun is attempted.
Ideally the exit code of the `go test` process would be 2 in this case, but until that changes we are forced to rely on string comparison of the output.
> Avoid rerun of failed tests when previous run had a panic

- testjson/execution.go
- testjson/execution_test.go
- testjson/testdata/go-test-json-missing-test-events.out
Inspired by the changes in #188
Fixes #141
Previously all missing events were reported. This commit omits events for any missing subtests pass events, so that subtests that passed do not show as failed.
The upstream bug was fixed in go1.16, so this mitigation probably does not need to stick around for long.
@aaronlehmann I added you as a co-author to this commit since this was heavily inspired by your change. I hope that is ok.
> Mitigate go test bug with missing subtest pass events 

- README.md
- cmd/main.go
- cmd/testdata/gotestsum-help-text
- testjson/execution.go
- testjson/execution_test.go
- testjson/testdata/go-test-json-with-nonjson-stdout.out
Adds a `ScanConfig` field `IgnoreNonJSONOutputLines`, enabled from the command line by `--ignore-non-json-output-lines`. It causes gotestsum to write non-JSON 'go test' output lines to `os.Stderr` instead of failing.
(For https://github.com/gotestyourself/gotestsum/issues/193. This is useful to handle underlying testing tools that mix `test2json` lines with other output and can't easily be changed to purely JSON.)
> Add IgnoreNonJSONOutputLines, `--ignore-non-json-output-lines`

- README.md
- cmd/watch.go
- internal/filewatcher/term_unix.go
- internal/filewatcher/term_windows.go
- internal/filewatcher/watch.go
- internal/filewatcher/watch_test.go
When files and directories are added, sometimes they won't be noticed because `gotestsum` only watches directories which already contained `.go` files. This new `l` action makes it possible to add these new directories without restarting `gotestsum`.
> watch: add action for reloading watched directory list

- internal/junitxml/report.go
- internal/junitxml/report_test.go
- internal/junitxml/testdata/junitxml-report.golden
- testjson/execution.go
The junit schema defines this attribute on the testsuite.
In my case I need to import test results totally separate from the
testing pipeline since these are in two different systems. This
timestamp ensures the result processor puts the results into the right
time frame instead of assuming it just ran.
Fixes #200
> junit: Add timestamp for suite start time

- go.mod
- go.sum
- testjson/dotformat.go
golang.org/x/crypto | CVE-2020-29652   | HIGH     | v0.0.0-20200622213623-75b288015ac9
> Fix cve-2020-29652

- cmd/main.go
- cmd/main_e2e_test.go
- cmd/main_test.go
- cmd/rerunfails_test.go
- cmd/watch.go
- main.go
Fixes #209 
This is a solution to fix the usability problem described in https://github.com/gotestyourself/gotestsum/issues/209.
Please provide any suggestions to improve the code quality. Thank you.
> fix(cmd/main.go): add a channel to proc{} for detecting SIGINT

- internal/junitxml/testdata/junitxml-report.golden
- testjson/dotformat_test.go
- testjson/execution.go
- testjson/execution_test.go
- testjson/format_test.go
- testjson/testdata/dots-format.out
Fixes #213
I'm not sure why I implemented it as the sum of test elapsed times. From what I can tell the package pass/fail event has always had the proper elapsed time. 
Using the time reported from the event should also be more accurate and include all the elapsed time from tests, as well as any time spent in `init`, `TestMain`,  or static declarations.
> Use the event elapsed time for package elapsed

- README.md
PR modifies the installation instructions to account for the deprecation of the `go get` method:
https://go.dev/doc/go-get-install-deprecation.
> update 'go get' idirective to 'go install'

- .golangci.yml
- internal/dotwriter/writer_posix.go
- internal/filewatcher/term_unix.go
golangci-lint passes like before.
> fix: remove deprecated linters from golanci-lint

- docs/running-without-go.md
With the current instructions you actually need a local go installation. Even if the go source is downloaded, a go binary is needed to compile test2json, even if it's a different version than the `test2json` one.
This PR adds instructions to download a temporary go binary, compile test2json from it and delete it.
> Instructions to compile `test2json` without local go

- .circleci/config.yml
Related to #236
Also changes the version used to release the binaries to go1.18.
> Add go1.18 to CI, and fix goreleaser install

- cmd/main_e2e_test.go
- cmd/testdata/e2e/expected/TestE2E_IgnoresWarnings
- cmd/testdata/e2e/ignore_warnings/ignore_warnings.go
- cmd/testdata/e2e/ignore_warnings/ignore_warnings_test.go
- testjson/execution.go
Proposal for skipping over warnings.
Elapsed times in golden files are causing this to fail.  It's also a pretty heavy-weight test for such a small change so maybe we should test this some other way.
Fixes #232
> Ensure we still rerun tests when there are warnings

- cmd/handler.go
- cmd/handler_test.go
- go.mod
Closes #238
If the directory can not be created then the file creation operation will fail as it did before.
No reason to force someone to create this directory ahead of time.
> Create any missing directories for {json,junit}file

- README.md
- cmd/main.go
- cmd/main_test.go
It may be useful to pipe the `go test` JSON to `gotestsum`. There are a few ways in which this could be achieved:
1. Passing stdin to `testjson.ScanConfig` seems the most sensible, but it may be complicated and may cause unintended side effects. For instance, assuming `gotestsum` were to contextually switch between using stdin and `go test`, existing invocations of `gotestsum` where data is being piped would no longer work. Providing a new flag to opt-in may be helpful? Maybe a sub-command?
2. (This PR) Passing stdin to `--raw-command` allows stdin to be piped to stdout via use of a tool like `cat`.
---
Given the changes included in this PR, `gotestsum` can read `go test` JSON via stdin with:
```sh
cat out.json | gotestsum --raw-command -- cat
```
This may be useful when the JSON is …
> Pass stdin to go test

- internal/filewatcher/term_aix.go
- internal/filewatcher/term_bsd.go
- internal/filewatcher/term_unix.go
- internal/filewatcher/watch.go
- internal/filewatcher/watch_unsupported.go
Fixes #244
Cross compiling worked:
```
GOOS=aix GOARCH=ppc64 go build .
```
Everything except for the `--watch` flag should work, but I can't test it.
> Fix the build on aix

- README.md
- cmd/watch.go
- internal/filewatcher/term_unix.go
- internal/filewatcher/watch.go
- internal/filewatcher/watch_test.go
- internal/filewatcher/watch_unix_test.go
While in watch mode, pressing `u` will rerun the tests with the `-update` flag. This makes it convenient to update expected values in golden files.
A bunch of golden libraries use this flag:
* the [stdlib](https://github.com/golangci/gofmt/blob/master/gofmt/gofmt_test.go#L20), and [hashicorp](https://github.com/hashicorp/consul/blob/main/agent/xds/golden_test.go#L18) projects define the flag in some test packages
* https://pkg.go.dev/gotest.tools/v3/golden (as soon as the next release is done)
* https://github.com/hexops/autogold
* https://pkg.go.dev/github.com/xorcare/golden
> watch: Add u key for updating golden values

- .golangci.yml
- cmd/handler_test.go
- go.mod
- go.sum
- internal/junitxml/report_test.go
- testjson/execution.go
- testjson/format.go
- testjson/format_test.go
- testjson/testdata/go-test-json-with-shuffle.err
- testjson/testdata/go-test-json-with-shuffle.out
- testjson/testdata/go-test.err
- testjson/testdata/pkgname-format-shuffle.out
- testjson/testdata/standard-quiet-format-shuffle.out
- testjson/testdata/standard-verbose-format-shuffle.out
- testjson/testdata/testname-format-shuffle.out
Closes #255
Show the shuffle seed when a package fails.
> Show shuffle seed

- .circleci/config.yml
- internal/dotwriter/writer.go
- testjson/doc.go
- testjson/execution.go
And update `gofmt` for new go.19 format.
Closes #183
Because go1.19 now includes these fixes in the stdlib: https://tip.golang.org/doc/go1.19#os-exec-path
> Test against go1.19, remove go1.15

- cmd/handler.go
- cmd/main.go
- cmd/testdata/gotestsum-help-text
- internal/junitxml/report.go
- internal/junitxml/report_test.go
- internal/junitxml/testdata/junitxml-report.golden
Add attributes `name`, `timestamp`, `tests`, `failures`, `errors`, `skipepd`, `time`, `hostname` to the `testsuites` xml node, according to the schema: https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd.
> Add project name to junit.xml output

- .project/goreleaser.yml
Added in support for `s390x` and `ppc64le` on Linux. 
In my testing I was able to see a successful build on CircleCI linked [here](https://app.circleci.com/pipelines/github/james-crowley/gotestsum/2/workflows/a72c6864-82b7-43d8-b920-2c2489a6ea75/jobs/11). This build allowed me to pull down the `s390x` artifact from CircleCI to validate a successful build.
```
linux1@circleci-runner-s390x:~$ wget https://output.circle-artifacts.com/output/job/a0e9cf72-e153-4b73-a04a-9eb6ef1f5499/artifacts/0/dist/gotestsum_linux_s390x/gotestsum && chmod +x gotestsum
linux1@circleci-runner-s390x:~$ ./gotestsum --version
gotestsum version 0.0.0-SNAPSHOT-85a7f9e
linux1@circleci-runner-s390x:~$ arch
s390x
```
Closes #268 
@dnephin Let me know if you need anything else for this PR to be merged. Happy to help!
> Adding in support for s390x and ppc64le

- cmd/main.go
- cmd/rerunfails.go
- cmd/testdata/gotestsum-help-text
- internal/text/testing.go
Related to #274
There was a hidden flag that did something similar, but I never fixed that flag to work correctly after changing `--rerun-fails` to run individual tests.  This PR fixes the logic to run only root test cases with failures (instead of running both root and subtests), renames the flag to `--rerun-fails-run-root-test`, and unhides it so that it shows up in help text.
> Add a flag for running the entire root test case when any of its subtests fail

- cmd/main.go
- cmd/main_test.go
`-failfast` stops the initial run of tests before all tests are run, so gotestsum never sees the full list of tests. When `gotestsum` goes to re-run tests, it uses the list of failed tests from the initial test run. Since only some of the tests ran, it never has the change to re-run all the tests that were skipped by `-failfast`.
`-failfast` has other problems (golang/go#30522, golang/go#33038).  If we wanted to support this combination of flags it is possible that `gotestsum` could get the list of tests from `go test --list`, however that introduces other problems. `go test --list` can be pretty slow, which adds more time to the overall test run. It also only lists top-level test cases, so there would be no way to re-run only failed subtests. That effectively makes the behaviour …
> Error if `-failfast` is used with `--rerun-fails`

- cmd/handler.go
- cmd/handler_test.go
- cmd/main.go
- cmd/testdata/gotestsum-help-text
- testjson/dotformat.go
- testjson/dotformat_test.go
- testjson/format.go
- testjson/format_test.go
- testjson/testdata/format/pkgname-hide-empty.out
Related to #228
Closes #282
Add a new `--format-hide-empty-pkg` flag to hide empty package in compact formats. The `testname` format should be verbose enough that a few extra `EMPTY` lines for packages is not a big deal, and the `standard` formats should emulate the `go test` output as close as possible, so we don't want it to apply to those. 
I tested both formats manually, and added golden tests for `pkgname`.
> Hide empty packages in compact formats

- cmd/tool/matrix/matrix.go
- cmd/tool/matrix/matrix_test.go
- internal/log/log.go
- main.go
This PR adds a new subcommand `gotestsum tool ci-matrix` for use with github actions.  The subcommand:
* reads `test2json` files saved in a github actions cache from previous test runs
* uses the `test2json` data to calculate the 85th percentile runtime of each package
* uses the package runtime to bucket all the packages into `n` buckets
A github actions workflow can then use those buckets in a [matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs), so that packages are split between the buckets based on their runtime. This should result in optimal splitting of packages to minimize overall CI runtime.
Using the subcommand requires integration with github actions, so I'll need to document exact how to wire it all together.  Once it's working well, maybe it …
> Add tool ci-matrix

- cmd/flags.go
- cmd/handler.go
- cmd/main.go
- cmd/testdata/gotestsum-help-text
- internal/junitxml/report.go
- internal/junitxml/report_test.go
- internal/junitxml/testdata/junitxml-report-skip-empty.golden
- testjson/dotformat.go
- testjson/execution.go
Followup to #282 and #283. I am leaving the failed golden test in here, because I think perhaps it might be a bug.  The original golden test output for junit.xml includes the following section, which my code hides:
```xml
<testsuite tests="0" failures="0" time="0.001000" name="gotest.tools/gotestsum/testjson/internal/badmain" timestamp="0001-01-01T00:00:00Z">
<properties>
<property name="go.version" value="go7.7.7"></property>
</properties>
<testcase classname="" name="TestMain" time="0.000000">
<failure message="Failed" type="">sometimes main can exit 2&#xA;FAIL&#x9;gotest.tools/gotestsum/testjson/internal/badmain&#x9;0.001s&#xA;</failure>
</testcase>
</testsuite>
```
This looks wrong to me, since `tests="0"` and `failures="0"`, yet there's clearly a failing testcase being simulated. Not …
> Hide empty packages on junit output

- .project/goreleaser.yml
fixes https://github.com/gotestyourself/gotestsum/issues/289
re: exclusion of `arm`
https://www.freebsd.org/platforms/arm/
> 32-bit ARMv6 and ARMv7 is officially a [Tier 2](https://docs.freebsd.org/en/articles/committers-guide/#archs) architecture, as the [FreeBSD](https://www.freebsd.org/) project does not provide official releases or pre-built packages for this platform due to it primarily targeting the embedded arena.
> 
> FreeBSD/arm64 supports 64-bit ARMv8 processors and is a [Tier 1](https://docs.freebsd.org/en/articles/committers-guide/#archs) architecture as of 13.0. 64-bit ARM platforms follow a set of standard conventions, and a single FreeBSD build will work on hardware from multiple vendors. As a result, FreeBSD provides official releases for FreeBSD/arm64 and packages are …
> feat(freebsd): generate arm/amd64 binaries for FreeBSD

- README.md
- cmd/main.go
- cmd/rerunfails.go
- cmd/rerunfails_test.go
- cmd/testdata/gotestsum-help-text
- cmd/watch.go
With the `--watch-chdir` flag, `gotestsum` will change the working directory
to the directory with the modified file before running tests. Changing the
directory is primarily useful when the project contains multiple Go modules.
Without this flag, `go test` will refuse to run tests for any package outside
of the main Go module.
> Add --watch-chdir flag

- README.md
- cmd/main.go
- cmd/testdata/gotestsum-help-text
- testjson/format.go
- testjson/format_test.go
- testjson/testdata/format/pkgname-hivis.out
The default icons used in the pkgname output formats (∅,✓,𐄂) can be hard to spot when scrolling through test output.
This PR adds the ability to pick a higher-visiblity/contrast set of icons (🔳,✅,❌) by adding a `-hivis` suffix to either of the 'pkgname' style formats.
> Add option to use high-visibility icons

- .project/golangci-lint.yml
- testjson/execution.go
- testjson/format.go
- testjson/summary_test.go
- testjson/testdata/input/go-test-json-panic-race.out
- testjson/testdata/summary/test-timeout-panic-race
This is a workaround for the race in `test2json`. See https://github.com/golang/go/issues/57305
Fixes #292
> Print the test timeout panic as package output

- internal/filewatcher/watch.go
- internal/filewatcher/watch_test.go
On OSX (12.6.2) using Neovim (NVIM v0.8.2) the triggering event varies between `fsnotify.Rename` and `Create`.
This fix adds `fsnotify.Rename` to the events triggering a new test run.
*Before*
```
handling event "cors_middleware.go": RENAME
handling event "cors_middleware.go": CREATE
Running tests in ./.
exec: [go test -json ./.]
go test pid: 96495
✓  . (cached)
DONE 71 tests in 0.237s
```
*After*
```
handling event "cors_middleware.go": RENAME
Running tests in ./.
exec: [go test -json ./.]
go test pid: 95707
✓  . (cached)
DONE 71 tests in 0.245s
```
> Fix need to save twice to trigger watch on OSX using Neovim

- cmd/handler.go
- cmd/handler_test.go
- cmd/main.go
- cmd/main_test.go
- cmd/watch.go
- testjson/format.go
While discussing the proposal in #303 I noticed the jsonfile is closed after running the `post-run-command`. In some cases, I think it's possible the post-run-command would read the file before all the contents of the file are flushed.
The test added in this commit seems to pass without these extra Flush, but from what I can tell there's no guarantee the file is sycned to disk without these new calls. Maybe that test would flake occasionally without these new calls to `Sync` ?
> Ensure jsonfile is flushed before running post-run-command

- internal/junitxml/report.go
- testjson/dotformat.go
- testjson/execution.go
- testjson/format.go
- testjson/format_test.go
PR #79 first introduced support for writing output directly to an `io.Writer` instead of creating large strings in memory. PR #313 added `eventFormatterFunc` so that formatters could be implemented as closures without needing a separate struct type for each.
This PR converts all the formatters to use this new type. There are still a few places where strings are constructed, but all of those strings should be small. The large strings (output from running tests) should be written directly to stdout, avoiding the need to allocate large strings that are discarded immediately after writing them.
> Use io.Writer in formatters

- cmd/tool/matrix/matrix.go
- cmd/tool/matrix/matrix_test.go
Github actions UI only shows the first few characters of the job name. The previous description resulted in the job names being mostly the same.
With this new description the more relevant parts of the name (the index and the primary package) should be more prominent.
> ci-matrix: improve description

- README.md
- cmd/tool/slowest/slowest.go
- cmd/tool/slowest/testdata/cmd-flags-help-text
- internal/aggregate/slowest.go
- internal/aggregate/slowest_test.go
By default `gotestsum tool slowest` prints the name of all tests slower than the threshold. This new flag allows someone to limit the output to the slowest `n` tests. This is likely most useful when combined with `--post-run-command` as shown in the new example. 
Closes #303
> slowest: Add num flag for limiting the number of slow tests to print

- .circleci/config.yml
Close https://github.com/gotestyourself/gotestsum/issues/323
I've confirmed the issue has been solved by updating goreleaser in my laptop.
```console
$ goreleaser --version
goreleaser version 1.17.0
commit: ffefd6c4ae257d2e9aeccb5786ba66401cc1bd78
built at: 2023-04-10T11:56:39Z
built by: goreleaser
goos: darwin
goarch: arm64
module version: v1.17.0, checksum: h1:CcA7EOcljdYhpEY2MUI1je6swCTCAlubxZk1VCbPKBY=
https://goreleaser.com
```
```console
$ goreleaser --clean --snapshot --config .project/goreleaser.yml
• starting release...
• loading config file                              file=.project/goreleaser.yml
• loading environment variables
• getting and validating git state
• building...                                    commit=6723d7d1d70e3e77d1032a027b3d87b8fb88be2d latest tag=v1.10.0
• …
```
> ci: update goreleaser 1.7.0 to 1.17.0 for windows/arm64

- testjson/execution.go
- testjson/format.go
- testjson/format_test.go
- testjson/internal/good/good.go
- testjson/internal/good/good_test.go
- testjson/testdata/format/pkgname-coverage-go1.20.out
- testjson/testdata/format/standard-quiet-coverage-go1.20.out
- testjson/testdata/input/go-test-json-with-cover-go1.20.err
- testjson/testdata/input/go-test-json-with-cover-go1.20.out
Fix #322
In go versions 1.19 and earlier the coverage details were always on a separate line. As of go1.20 they are after a tab on the same line as the package name.
> Fix coverage detection for go1.20

- cmd/rerunfails.go
- cmd/rerunfails_test.go
Fixes #337: The (sub) test names were not quoted before being used within the regex passed to `-run` and therefore caused `go test` to mis-evaluate the expression if there were parentheses contained. Uses https://pkg.go.dev/regexp#QuoteMeta to make it work for a wider range of characters.
> Quote test names before they are used within the regex to rerun

- testjson/execution.go
- testjson/execution_test.go
Teaching `gotestsum` to recognize Golang cache debug output. When `gocachehash=1` or `gocachetest=1` debug options are enabled, output is sent to `stderr`. `gotestum` treats unrecognised `stderr` messages as errors what makes test suite run marked as failed.
Example of testing `gotestsum` repository without this PR. Each debug info line is treated as error:
```shell
$ GODEBUG=gocachehash=1,gocachetest=1 ./gotestsum
...
DONE 183 tests, 2 skipped, 13819 errors in 0.726s
```
After fixing the issue:
```shell
$ GODEBUG=gocachehash=1,gocachetest=1 ./gotestsum
...
DONE 183 tests, 2 skipped in 0.523s
```
> Don't treat debug messages as errors

- cmd/rerunfails.go
- cmd/rerunfails_test.go
Addresses part of the issue in #341
> handle multiple levels in subtest regex generation

- testjson/execution.go
- testjson/execution_test.go
> rerun-fails: prevent extra runs when a sub-test fails

- internal/dotwriter/writer.go
- internal/dotwriter/writer_posix.go
- internal/dotwriter/writer_windows.go
- testjson/testdata/format/dots-v2.out
Contributes to https://github.com/gotestyourself/gotestsum/issues/352
Currently, as the new screen is written the cursor jumps around the terminal. This hides it, writes everything else, then returns it.
Prior art:
https://github.com/docker/compose/blob/80856eacafcf96d6f27e74c07e42386fe662f8ef/pkg/progress/tty.go#L160-L162
> dots-v2: hide cursor during output

- cmd/handler.go
> Fix dots formats with stderr

- internal/dotwriter/writer.go
- internal/dotwriter/writer_posix.go
- internal/dotwriter/writer_windows.go
- testjson/testdata/format/dots-v2.out
As best I can tell, this fully fixes https://github.com/gotestyourself/gotestsum/issues/352
While there were a variety of workarounds I tried to fix this, which had some improvement, the real root cause is doing `clear screen; write`. This leaves some time where each cell in the terminal goes from `<something> -> empty -> <something>`, which leads to blinking.
Instead, we can write and clear as we go. This has the same end result, but avoids the intermediate step where we have an empty cell.
This PR is probably not acceptable as-is as it doesn't even compile on windows. Not sure the best steps there, I neither have experience with implementing this in windows nor a machine to test on. We could keep the old implementation for windows, possibly.
> dotsv2: remove jitters entirely

- internal/filewatcher/watch.go
Although unlikely, it is possible for os.Stat to fail in handleDirCreated. The two most likely causes are a symlink to a target that doesn't exist or a race condition with a process that deletes the path.
In any case, it isn't actionable by the user and causes no harm to ignore the error.
Refs: #370
> filewatcher: silence warning from os.Stat failures

- .project/goreleaser.yml
- internal/filewatcher/term_illumos.go
Please consider adding support for illumos-based operating systems such as OmniOS, OpenIndiana, SmartOS, etc. I tested to make sure things build correctly and validated that the tool works correctly on a couple of versions of OmniOS. Addition of `internal/filewatcher/term_illumos.go` was necessary to correctly build, and I apologize, but these constants are not available from `golang.org/x/sys/unix`, thus I supplied literal values instead. These values have not changed in at least 20 years, likely much longer.
> Add support for gotestsum on illumos/amd64

- internal/filewatcher/term_unix.go
As discussed in a [comment](https://github.com/gotestyourself/gotestsum/issues/370#issuecomment-1724656425), update the warning message to be slightly more useful to the user by mentioning the impact of the error rather than just the cause.
Because `go test` captures Stderr & Stdout and redirects Stdin, it provides a handy repro. Without this change:
```console
$ go test
Running tests in ./.
Watching 1 directories. Use Ctrl-c to to stop a run or exit.
WARN failed to put terminal (fd 0) into raw mode: operation not supported by device
```
With this change:
```console
$ go test
Watching 1 directories. Use Ctrl-c to to stop a run or exit.
WARN no terminal input -- keyboard shortcuts disabled: operation not supported by device
```
I am happy to change the text if the maintainers can suggest …
> Improve warning message when stdin is not a terminal

- internal/filewatcher/term_illumos.go
This is based on feedback from @smoynes. I validated that these constants are correctly selected with `GOOS=illumos` this makes the code more consistent with other already existing OS-specific code in the `filewatcher` package.
> Used named constants instead of magic numbers in illumos-specific code

- testjson/execution.go
- testjson/execution_test.go
If someone creates a test name with `/` in the name, then it is possible to end up with a hierarchy with a gap. For example, if someone creates a subtest of `TestParent` with the name `child/grandchild` and it fails, then the two failing tests will be `TestParent` and `TestParent/child/grandchild`. This breaks `FilterFailedUnique` and will cause it not to filter out `TestParent` which means that all child tests will get rerun. This PR fixes this by updating the `parents` to include all the parents of the given test case. 
If you're curious for why someone would be doing this, I don't think there is any strong requirement for people to do this, but [personally I do it in hishtory](https://github.com/ddworken/hishtory/blob/9433bd6e944c4b59d487e740d271c1e4a63b5bb5/client/client_test.go#L62-L6 …
> Update gotestsum retries to properly filter out parents when there is a a missing gap in the parent tree

- cmd/main.go
[Woodpecker CI](https://github.com/woodpecker-ci/woodpecker) is a fork of Drone and also supports colors in the CI output.
> Add Woodpecker CI to no-color default autodetection

- README.md
The team at https://github.com/gofiber/fiber are using `gotestsum` to better visualize our suite of over +1k unit-tests.
> Add gofiber/fiber to list of projects

- testjson/dotformat_test.go
Seems reliable on linux, but recent PRs have had failures on macos runners.
> Skip test that is falky on macos

- cmd/goversion_go122.go
This reads to me that the current running version is at least equal to the provided version in variable 'v'. In it's current form isGoVersionAtLeast will return false when go runtime is go1.23.0 and supplied string is go1.22 (which is what is being tested for now). 
I swapped the x,y to match the function name intent. I couldn't find any notes in diff if we wanted to explicitly not support 1.23 and later.
`func isGoVersionAtLeast(v string) bool {
return goversion.Compare(v, runtime.Version()) < 0
}
`
> Fix incorrect minVersion check - Bug here is either the function is misnamed or the logic is inverted

- .project/golangci-lint.yml
- cmd/handler.go
- cmd/handler_test.go
- cmd/main.go
- cmd/main_e2e_test.go
- cmd/rerunfails.go
- cmd/tool/matrix/matrix_test.go
- cmd/watch.go
- internal/aggregate/slowest.go
- internal/filewatcher/watch.go
- testjson/dotformat.go
- testjson/execution.go
- testjson/execution_test.go
- testjson/format.go
- testjson/summary.go
The PR removes unused `//nolint` directives found with [`nolintlint`](https://golangci-lint.run/usage/linters/#nolintlint). Also, remove spaces between `nolint` and the linter name as `nolintlint` suggests.
> Clean up nolint directives

- cmd/handler_test.go
- cmd/main_e2e_test.go
- cmd/testdata/e2e/expected/TestE2E_RerunFails/first_run_has_errors,_abort_rerun-go1.19
- cmd/testdata/e2e/expected/TestE2E_RerunFails/first_run_has_errors,_abort_rerun-go1.23
- cmd/testdata/e2e/expected/TestE2E_RerunFails/reruns_continues_to_fail-go1.23
- cmd/testdata/e2e/expected/TestE2E_RerunFails/reruns_until_success-go1.23
- cmd/testdata/expected/build-fail-expected
- cmd/testdata/expected/setup-fail-expected
- cmd/testdata/input/go-test-build-failed.out
- cmd/testdata/input/go-test-setup-failed.out
- testjson/execution.go
Closes #469
Related to #474
Build errors are no longer in stderr and are now part of the JSON.
This PR doesn't attempt to put the build errors into the package where they failed, it simply shows them under "=== Errors" as it did before.
I opened #475, because I guess it should now be possible to include the JSON errors in the junitxml under the package that caused them.
> Include new json build failures  (go1.24)

- README.md
- cmd/main.go
- cmd/rerunfails.go
- cmd/rerunfails_test.go
- cmd/testdata/gotestsum-help-text
- testjson/execution.go
This PR implements the `--rerun-fails-abort-on-data-race` flag. When a race condition is detected, the flag stops re-running failed tests and fails the entire test run.
My motivation for adding this flag is to let `gotestsum` work with race tests that should fail when a data race is found but retry when a test fails for other reasons. In my specific use case, I run a CI test suite where some tests fail due to transient issues, such as network errors; those can be retried and do not require an engineer’s attention. A race condition, however, signals a bug in concurrent code and should notify an engineer.
> feat: add the `--rerun-fails-abort-on-data-race` flag

- cmd/main.go
Currently, the version information is provided via `ldflags`, which does not work for users who install `gotestsum` using `go install`. This PR changes the version retrieval to use the `fmt/debug` package, allowing users to see the correct version information regardless of the installation method.
Example output for a local build:
```bash
> gotestsum --version
gotestsum version (devel)
```
Example output when installed with go install:
```bash
> gotestsum --version
gotestsum version v1.7.5
```
Related Issue: https://github.com/gotestyourself/gotestsum/issues/503
> Show correct version when installed via `go install`

- cmd/main.go
After https://github.com/gotestyourself/gotestsum/pull/520, the use case of setting the version when building from a Git tarball (which contains the repo contents, but not the VCS information) is broken, leaving the version as `(devel)`.
This change returns the option to manually set the version via ldflags. If this manual value is not set (remains empty), then the value from `debug.ReadBuildInfo()` is used.
> Allow version to be configured at build time
